### ISSUE TITLE
Use Equatable

### ISSUE THREAD

**Issue by mahmoud-eslami** [Amirnlz/Crypto-coin#1]
Hi ,
I checked your code and that was amazing 🔥 but it seems you didn't use `equitable` for events and states of blocs, I suggest using `equitable` because it overrides `==` and `hashCode` internally, which saves a lot of boilerplate code.

e.g. 

```dart
abstract class LoginStates extends Equatable{}
 ```
```dart
class LoginData extends LoginStates {
  final bool status;
  final String userName;
  const LoginData({this.status, this.userName});
  @override
  List<Object> get props => [this.status, this.userName];
}
```

**Comment by Amirnlz** [comment]
Hello @mahmoud-eslami,
Thanks for issue, yes, I haven't used because at that moment I haven't known the benefits of usage. I will try and learn how and why to use `equitable` and I will add to blocs as soon as possible.
